mykey = "konzek"
ami = "ami-0889a44b331db0194"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "konzek-jenkins-server-secgr"
jenkins-server-tag = "Jenkins Server of konzek"
jenkins-profile = "konzek-jenkins-server-profile"
jenkins-role = "konzek-jenkins-server-role"