# Database microservice Dockerfile

# Base image
FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=konzek
ENV MYSQL_USER=konzek_user
ENV MYSQL_PASSWORD=konzek_password

# Expose port
EXPOSE 3306
