# Database microservice Dockerfile

# Base image
FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=petclinic
ENV MYSQL_USER=petclinic_user
ENV MYSQL_PASSWORD=petclinic_password

# Expose port
EXPOSE 3306
